### ISSUE TITLE
The version specified in the readme does not have the latest feature

### ISSUE THREAD

**Issue by keychera** [babashka/http-server#11]
In the [readme][1], it specifies `{:mvn/version "0.1.11"}` for dependency and the next command provided uses the recently added `:headers` flag feature, which is actually not  in the version `0.1.11` . The simple workaround is to use git deps like this:

```edn
{:deps {org.babashka/http-server {:git/url "https://github.com/babashka/http-server.git"
                                  :sha "c8f061a9ad12f0381981e280266846117295154e"}}}
```

I don't know what fix is better, whether to update the readme to use sha or to make a new release. So I am making this issue first just in case someone else needs it.

[1]: https://github.com/babashka/http-server/blob/c8f061a9ad12f0381981e280266846117295154e/README.md

**Comment by borkdude** [comment]
released 0.1.12
