### ISSUE TITLE
problems with using --headers

### ISSUE THREAD

**Issue by lwiechec** [babashka/http-server#12]
I am having trouble adding extra headers (added by #8). For example. using `http-server` (as described [here](https://github.com/babashka/http-server/#babashka)) - when I start it like this: `http-server --dir "." --port 9998 --headers '{X-SomeHeader" "value"}'`, I do not see the header anywhere:

```
[luke:~] 7 $ curl -v http://localhost:9999
* Host localhost:9999 was resolved.
* IPv6: ::1
* IPv4: 127.0.0.1
*   Trying [::1]:9999...
* Connected to localhost (::1) port 9999
> GET / HTTP/1.1
> Host: localhost:9999
> User-Agent: curl/8.5.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< content-length: 1488
< Server: http-kit
< Date: Thu, 8 Feb 2024 15:29:03 GMT
< 
<html><head>...
```
I am using babashka v1.3.186.

Maybe I am not using it correctly ?

**Comment by borkdude** [comment]
Does it make a difference when using a string key instead of a symbol key?

**Comment by borkdude** [comment]
Got it: the headers are currently only returned when a file is retrieved:

```
$ curl -I http://localhost:8090/README.md
HTTP/1.1 200 OK
X-Foo-Bar: bar
content-length: 2558
Server: http-kit
Date: Thu, 8 Feb 2024 15:40:24 GMT
```

**Comment by lwiechec** [comment]
thank you @borkdude for a quick check! I was too confused to try with getting a file...

**Comment by borkdude** [comment]
I changed the logic to always return the headers on every response.
