### ISSUE TITLE
Support range requests

### ISSUE THREAD

**Issue by jmglov** [babashka/http-server#16]
When a browser makes a range request such as this:

``` text
GET /Garth+Brooks/Fresh+Horses/Garth+Brooks+-+The+Old+Stuff.mp3 HTTP/1.1
Range: bytes=0-
```
According to our good friends over at the [Mozilla Developer Network](https://developer.mozilla.org/en-US/docs/Web/HTTP/Range_requests), it expects a response like this:

``` text
HTTP/1.1 206 Partial Content
Accept-Ranges: bytes
Content-length: 1048576
Content-Range: bytes 0-1048575/5943424
Content-Type: audio/mpeg
```

However, http-server currently returns this:

``` text
HTTP/1.1 200 OK
Content-length: 5943424
Content-Type: audio/mpeg
Server: http-kit
```

with a bunch of bytes in the body. In fact, a bountiful buffet of beautiful bytes, five whole million of them! And another 943,424 thrown in for dessert.

This means that the standard HTTP `<audio>` tag player thingy refuses to seek in the file, instead jumping back to the beginning of the file every time one tries. :scream: 

It would be lovely, bordering on spectacular, if http-server supported this. And I think I know just the guy to implement that support and then vomit out 7000 words about it. :roll_eyes:

**Comment by jmglov** [comment]
Never fear friends, I'm on it!

**Comment by borkdude** [comment]
Awesome!
