### ISSUE TITLE
Rename to file-server?

### ISSUE THREAD

**Issue by borkdude** [babashka/http-server#2]
file-server seems a more appropriate name for this project

**Comment by delyada** [comment]
Might make sense. I came here after tripping on this, and searching for a bit more config knobs.

![image](https://user-images.githubusercontent.com/70277581/201771755-ed4639ce-d55c-4ac5-a1b3-293531173a11.png)

In this app under "serve", `login` is a dynamic route.

**Comment by borkdude** [comment]
Too late now, I guess
