### ISSUE TITLE
Unescape URLs?

### ISSUE THREAD

**Issue by orestis** [babashka/http-server#3]
I am serving some crawled assets that contain URLs like:

`../assets/css/screen.css%3Fv=bdeae747df.css` - the file in the filesystem is named `screen.css`.

If I edit the link to `../assets/css/screen.css?v=bdeae747df.css` then the file is loaded fine, otherwise it's a 404. I'm not 100% sure on if this is correct behaviour, but I expect that web-servers should un-escape URLs?

**Comment by borkdude** [comment]
@orestis I don't think that's how it should work. If you escape the query parameter question mark, it means you want to visit the route that includes a question mark. I confirmed this using Python's http-server:

<img width="716" alt="Screenshot 2022-11-26 at 18 43 09" src="https://user-images.githubusercontent.com/284934/204102006-95a8130a-f62c-45e2-b55c-c7f80931f1ed.png">
